  name: CI - Pruebas Unitarias Run Pytest
  run-name: Run Pytest con Python
  on:
    push:
      branches:
        - main
    pull_request:
      branches:
        - main

  jobs:
    test:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: '3.10'

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

        - name: Run Pytest
          run: PYTHONPATH=. pytest --junitxml=report.xml

        - name: Generar Template Prueba Unitaria
          run: python3 generate_test.py
       
        - name: Notificar en Pull Request sobre nueva prueba generada
          if: github.event_name == 'pull_request'
          uses: actions/github-script@v6
          with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
            script: |
                github.issues.createComment({
                  issue_number: context.payload.pull_request.number,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  body: "⚠️ Se ha generado un nuevo template de prueba unitaria. **Por favor, revisa y ejecuta las pruebas antes de continuar con la integración.** 🚀"
                })       

        - name: Upload Test Report
          uses: actions/upload-artifact@v4
          with:
            name: pytest-report
            path: report.xml
